services:
  jenkins:
    image: kaikfreitas/s07-jenkins:latest
    container_name: s07-jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/login" ]
      interval: 10s
      timeout: 5s
      retries: 5

  agent:
    build:
      context: .
      dockerfile: dockerfile.agent
    container_name: s07-jenkins-agent
    restart: unless-stopped
    environment:
      JENKINS_URL: http://jenkins:8080
      JENKINS_SECRET: f07b8514015a2caea6647b7796b29f965db589a929577cc0f38038ba8ecd7a60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins

  newman:
    build:
      context: .
      dockerfile: dockerfile.newman
    container_name: s07-newman
    restart: unless-stopped
    volumes:
      - ./postman:/etc/newman

  nginx:
    build:
      context: .
      dockerfile: dockerfile.nginx
    container_name: s07-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - jenkins

volumes:
  jenkins_data:
